[theme]
primaryColor = "#FF4B4B"                  
backgroundColor = "#E5FCFF"              
secondaryBackgroundColor = "#FFFFF"     
textColor = "#5E061B"                     
font = "sans serif"                       
