[theme]
primaryColor = "#FF4B4B"                  
backgroundColor = "#AADEF2"              
secondaryBackgroundColor = "#FFFFF"     
textColor = "#5E061B"                     
font = "serif"                       
